name: Publish to WinGet - stable builds
on:
  release:
    types: [released]
  workflow_dispatch:
    inputs:
      version:
        type: string
        required: true
        description: Version
jobs:
  publish:
    runs-on: windows-latest
    steps:
      - name: Publish smtp4dev to WinGet
        uses: vedantmgoyal9/winget-releaser@main
        with:
          identifier: Rnwood.Smtp4dev
          installers-regex: 'Rnwood.Smtp4dev-win-(x64|arm64)-.*\.zip'
          token: ${{ secrets.WINGET_TOKEN }}
          version: ${{ inputs.version }}
          release-tag: ${{ inputs.version }}
      - name: Publish smtp4dev.Desktop to WinGet
        uses: vedantmgoyal9/winget-releaser@main
        with:
          identifier: Rnwood.Smtp4dev.Desktop
          installers-regex: 'Rnwood.Smtp4dev.Desktop-win-x64-.*\.zip'
          token: ${{ secrets.WINGET_TOKEN }}
          version: ${{ inputs.version }}
          release-tag: ${{ inputs.version }}
